/* Fix deprecated fetaures */

ALTER TABLE [dbo].[tblIsolate] ALTER COLUMN [Comment] VARCHAR(MAX) NULL;
ALTER TABLE [dbo].[tblIsolate] ALTER COLUMN [PhylogeneticAnalysis] VARCHAR(MAX) NULL;
ALTER TABLE [dbo].[tblLogIsolate] ALTER COLUMN [Comment] VARCHAR(MAX) NULL;
ALTER TABLE [dbo].[tblLogIsolate] ALTER COLUMN [PhylogeneticAnalysis] VARCHAR(MAX) NULL;
ALTER TABLE [dbo].[tblSysInfo] ALTER COLUMN [ReleaseNotes] VARCHAR(MAX) NULL;



ALTER TABLE [tblCharacteristic] ALTER COLUMN [CharacteristicId] DROP ROWGUIDCOL;
ALTER TABLE [tblDispatch] ALTER COLUMN [DispatchId] DROP ROWGUIDCOL;
ALTER TABLE [tblIsolate] ALTER COLUMN [IsolateId] DROP ROWGUIDCOL;
ALTER TABLE [tblIsolateViability] ALTER COLUMN [IsolateViabilityId] DROP ROWGUIDCOL;
ALTER TABLE [tblLogCharacteristic] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblLogDispatch] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblLogIsolate] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblLogIsolateViability] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblLogSample] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblLogSubmission] ALTER COLUMN [LogID] DROP ROWGUIDCOL;
ALTER TABLE [tblSample] ALTER COLUMN [SampleId] DROP ROWGUIDCOL;
ALTER TABLE [tblSubmission] ALTER COLUMN [SubmissionId] DROP ROWGUIDCOL;
ALTER TABLE [tblSysInfo] ALTER COLUMN [ID] DROP ROWGUIDCOL;
ALTER TABLE [tlkpCountry] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpFreezer] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpHostBreed] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpHostPurpose] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpHostSpecies] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpIsolationMethod] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpLookup] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpSampleType] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpSender] ALTER COLUMN [SenderID] DROP ROWGUIDCOL;
ALTER TABLE [tlkpStaff] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpSubmissionReason] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpSubmittingLab] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpTray] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpViability] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpVirusCharacteristic] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpVirusFamily] ALTER COLUMN [Id] DROP ROWGUIDCOL;
ALTER TABLE [tlkpVirusType] ALTER COLUMN [Id] DROP ROWGUIDCOL;

ALTER TABLE dbo.tblLogCharacteristic ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tblLogDispatch ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tblLogIsolate ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tblLogIsolateViability ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tblLogSample ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tblLogSubmission ALTER COLUMN UserID VARCHAR(128) NOT NULL;
ALTER TABLE dbo.tmpMissingIsolate ALTER COLUMN userId VARCHAR(128) NOT NULL;

ALTER TABLE [dbo].[tblIsolate] ALTER COLUMN [CreatedBy]  VARCHAR(128)  NULL;
ALTER TABLE [dbo].[tblLogIsolate] ALTER COLUMN [CreatedBy]  VARCHAR(128)  NULL;
ALTER TABLE [dbo].[tmpMissingIsolate] ALTER COLUMN [loginBy]  VARCHAR(128)  NULL;
